export class Region{
    public regions = [
        {value: 'AFGHANISTAN', viewValue: 'Afghanistan'},
        {value: 'ALBANIA', viewValue: 'Albania'},
        {value: 'ALGERIA', viewValue: 'Algeria'},
        {value: 'AMERICAN_SAMOA', viewValue: 'American Samoa'},
        {value: 'ANDORRA', viewValue: 'Andorra'},
        {value: 'ANGOLA', viewValue: 'Angola'},
        {value: 'ANGUILLA', viewValue: 'Anguilla'},
        {value: 'ANTARCTICA', viewValue: 'Antarctica (the territory South of 60 deg S)'},
        {value: 'ANTIGUA_AND_BARBUDA', viewValue: 'Antigua and Barbuda'},
        {value: 'ARGENTINA', viewValue: 'Argentina'},
        {value: 'ARMENIA', viewValue: 'Armenia'},
        {value: 'ARUBA', viewValue: 'Aruba'},
        {value: 'AUSTRALIA', viewValue: 'Australia'},
        {value: 'AUSTRIA', viewValue: 'Austria'},
        {value: 'AZERBAIJAN', viewValue: 'Azerbaijan'},
        {value: 'BAHAMAS', viewValue: 'Bahamas'},
        {value: 'BAHRAIN', viewValue: 'Bahrain'},
        {value: 'BANGLADESH', viewValue: 'Bangladesh'},
        {value: 'BARBADOS', viewValue: 'Barbados'},
        {value: 'BELARUS', viewValue: 'Belarus'},
        {value: 'BELGIUM', viewValue: 'Belgium'},
        {value: 'BELIZE', viewValue: 'Belize'},
        {value: 'BENIN', viewValue: 'Benin'},
        {value: 'BERMUDA', viewValue: 'Bermuda'},
        {value: 'BHUTAN', viewValue: 'Bhutan'},
        {value: 'BOLIVIA', viewValue: 'Bolivia'},
        {value: 'BOSNIA', viewValue: 'Bosnia and Herzegovina'},
        {value: 'BOTSWANA', viewValue: 'Botswana'},
        {value: 'BOUVET_ISLAND', viewValue: 'Bouvet Island (Bouvetoya)'},
        {value: 'BRAZIL', viewValue: 'Brazil'},
        {value: 'BRITISH_INDIAN_OCEAN', viewValue: 'British Indian Ocean Territory (Chagos Archipelago)'},
        {value: 'BRUNEI', viewValue: 'Brunei Darussalam'},
        {value: 'BULGARIA', viewValue: 'Bulgaria'},
        {value: 'BURKINA_FASO', viewValue: 'Burkina Faso'},
        {value: 'BURUNDI', viewValue: 'Burundi'},
        {value: 'CAMBODIA', viewValue: 'Cambodia'},
        {value: 'CAMEROON', viewValue: 'Cameroon'},
        {value: 'CANADA', viewValue: 'Canada'},
        {value: 'CAPE_VERDE', viewValue: 'Cape Verde'},
        {value: 'CAYMAN', viewValue: 'Cayman Islands'},
        {value: 'CENT_AFRICAN_REP', viewValue: 'Central African Republic'},
        {value: 'CHAD', viewValue: 'Chad'},
        {value: 'CHILE', viewValue: 'Chile'},
        {value: 'CHINA', viewValue: 'China'},
        {value: 'CHRISTMAS_ISLAND', viewValue: 'Christmas Island'},
        {value: 'COCOS', viewValue: 'Cocos (Keeling) Islands'},
        {value: 'COLOMBIA', viewValue: 'Colombia'},
        {value: 'COMOROS', viewValue: 'Comoros'},
        {value: 'CONGO', viewValue: 'Congo'},
        {value: 'COOK', viewValue: 'Cook Islands'},
        {value: 'COSTA_RICA', viewValue: 'Costa Rica'},
        {value: 'COTE_IVOIRE', viewValue: 'Cote d\'Ivoire'},
        {value: 'CROATIA', viewValue: 'Croatia'},
        {value: 'CUBA', viewValue: 'Cuba'},
        {value: 'CYPRUS', viewValue: 'Cyprus'},
        {value: 'CZECH', viewValue: 'Czech Republic'},
        {value: 'DPR_KOREA', viewValue: 'Democratic People\'s Republic of Korea'},
        {value: 'DENMARK', viewValue: 'Denmark'},
        {value: 'DIJBOUTI', viewValue: 'Djibouti'},
        {value: 'DOMINICA', viewValue: 'Dominica'},
        {value: 'DOMINICAN_REP', viewValue: 'Dominican Republic'},
        {value: 'ECUADOR', viewValue: 'Ecuador'},
        {value: 'EGYPT', viewValue: 'Egypt'},
        {value: 'EL_SALVADOR', viewValue: 'El Salvador'},
        {value: 'EQUATORIAL_GUINEA', viewValue: 'Equatorial Guinea'},
        {value: 'ERITREA', viewValue: 'Eritrea'},
        {value: 'ESTONIA', viewValue: 'Estonia'},
        {value: 'ETHIOPIA', viewValue: 'Ethiopia'},
        {value: 'FALKLAND', viewValue: 'Falkland Islands (Malvinas)'},
        {value: 'FAROE', viewValue: 'Faroe Islands'},
        {value: 'FIJI', viewValue: 'Fiji'},
        {value: 'FINLAND', viewValue: 'Finland'},
        {value: 'FRANCE', viewValue: 'France'},
        {value: 'FRENCH_GUINEA', viewValue: 'French Guiana'},
        {value: 'FRENCH_POLYNESIA', viewValue: 'French Polynesia'},
        {value: 'FRENCH_SOUTH_TERRITORIES', viewValue: 'French Southern Territories'},
        {value: 'GABON', viewValue: 'Gabon'},
        {value: 'GAMBIA', viewValue: 'Gambia'},
        {value: 'GEORGIA', viewValue: 'Georgia'},
        {value: 'GERMANY', viewValue: 'Germany'},
        {value: 'GHANA', viewValue: 'Ghana'},
        {value: 'GIBRALTAR', viewValue: 'Gibraltar'},
        {value: 'GREECE', viewValue: 'Greece'},
        {value: 'GREENLAND', viewValue: 'Greenland'},
        {value: 'GRENADA', viewValue: 'Grenada'},
        {value: 'GUADELOUPE', viewValue: 'Guadeloupe'},
        {value: 'GUAM', viewValue: 'Guam'},
        {value: 'GUATEMALA', viewValue: 'Guatemala'},
        {value: 'GUERNSEY', viewValue: 'Guernsey'},
        {value: 'GUINEA', viewValue: 'Guinea'},
        {value: 'GUINEA_BISSAU', viewValue: 'Guinea-Bissau'},
        {value: 'GUYANA', viewValue: 'Guyana'},
        {value: 'HAITI', viewValue: 'Haiti'},
        {value: 'HEARD_MCDONALD_ISLANDS', viewValue: 'Heard Island and McDonald Islands'},
        {value: 'HOLY_SEE', viewValue: 'Holy See (Vatican City State)'},
        {value: 'HONDURAS', viewValue: 'Honduras'},
        {value: 'HONG_KONG', viewValue: 'Hong Kong'},
        {value: 'HUNGARY', viewValue: 'Hungary'},
        {value: 'ICELAND', viewValue: 'Iceland'},
        {value: 'INDIA', viewValue: 'India'},
        {value: 'INDONESIA', viewValue: 'Indonesia'},
        {value: 'IRAN', viewValue: 'Iran'},
        {value: 'IRAQ', viewValue: 'Iraq'},
        {value: 'ISLE_MAN', viewValue: 'Isle of Man'},
        {value: 'ISRAEL', viewValue: 'Israel'},
        {value: 'ITALY', viewValue: 'Italy'},
        {value: 'JAMAICA', viewValue: 'Jamaica'},
        {value: 'JAPAN', viewValue: 'Japan'},
        {value: 'JERSEY', viewValue: 'Jersey'},
        {value: 'JORDAN', viewValue: 'Jordan'},
        {value: 'KAZAKHSTAN', viewValue: 'Kazakhstan'},
        {value: 'KENYA', viewValue: 'Kenya'},
        {value: 'KIRIBATI', viewValue: 'Kiribati'},
        {value: 'KUWAIT', viewValue: 'Kuwait'},
        {value: 'KYRGYZ', viewValue: 'Kyrgyz Republic'},
        {value: 'LAO', viewValue: 'Lao People\'s Democratic Republic'},
        {value: 'LATVIA', viewValue: 'Latvia'},
        {value: 'LEBANON', viewValue: 'Lebanon'},
        {value: 'LESOTHO', viewValue: 'Lesotho'},
        {value: 'LIBERIA', viewValue: 'Liberia'},
        {value: 'LIBYAN_ARAB_JAMAHIRIYA', viewValue: 'Libyan Arab Jamahiriya'},
        {value: 'LIECHTENSTEIN', viewValue: 'Liechtenstein'},
        {value: 'LITHUANIA', viewValue: 'Lithuania'},
        {value: 'LUXEMBOURG', viewValue: 'Luxembourg'},
        {value: 'MACAO', viewValue: 'Macao'},
        {value: 'MACEDONIA', viewValue: 'Macedonia'},
        {value: 'MADAGASCAR', viewValue: 'Madagascar'},
        {value: 'MALAWI', viewValue: 'Malawi'},
        {value: 'MALAYSIA', viewValue: 'Malaysia'},
        {value: 'MALDIVES', viewValue: 'Maldives'},
        {value: 'MALI', viewValue: 'Mali'},
        {value: 'MALTA', viewValue: 'Malta'},
        {value: 'MARSHALL', viewValue: 'Marshall Islands'},
        {value: 'MARTINIQUE', viewValue: 'Martinique'},
        {value: 'MAURITANIA', viewValue: 'Mauritania'},
        {value: 'MAURITIUS', viewValue: 'Mauritius'},
        {value: 'MAYOTTE', viewValue: 'Mayotte'},
        {value: 'MEXICO', viewValue: 'Mexico'},
        {value: 'MICRONESIA', viewValue: 'Micronesia'},
        {value: 'MOLDOVA', viewValue: 'Moldova'},
        {value: 'MONACO', viewValue: 'Monaco'},
        {value: 'MONGOLIA', viewValue: 'Mongolia'},
        {value: 'MONTENEGRO', viewValue: 'Montenegro'},
        {value: 'MONTSERRAT', viewValue: 'Montserrat'},
        {value: 'MOROCCO', viewValue: 'Morocco'},
        {value: 'MOZAMBIQUE', viewValue: 'Mozambique'},
        {value: 'MYANMAR', viewValue: 'Myanmar'},
        {value: 'NAMIBIA', viewValue: 'Namibia'},
        {value: 'NAURU', viewValue: 'Nauru'},
        {value: 'NEPAL', viewValue: 'Nepal'},
        {value: 'NETHERLANDS', viewValue: 'Netherlands'},
        {value: 'ANTILLES', viewValue: 'Netherlands Antilles'},
        {value: 'NEW_CALEDONIA', viewValue: 'New Caledonia'},
        {value: 'NEW_ZEALAND', viewValue: 'New Zealand'},
        {value: 'NICARAGUA', viewValue: 'Nicaragua'},
        {value: 'NIGER', viewValue: 'Niger'},
        {value: 'NIGERIA', viewValue: 'Nigeria'},
        {value: 'NIUE', viewValue: 'Niue'},
        {value: 'NORFOLK', viewValue: 'Norfolk Island'},
        {value: 'MARIANA', viewValue: 'Northern Mariana Islands'},
        {value: 'NORWAY', viewValue: 'Norway'},
        {value: 'OMAN', viewValue: 'Oman'},
        {value: 'PAKISTAN', viewValue: 'Pakistan'},
        {value: 'PALAU', viewValue: 'Palau'},
        {value: 'PALESTINIAN', viewValue: 'Palestinian Territory'},
        {value: 'PANAMA', viewValue: 'Panama'},
        {value: 'PAPUA', viewValue: 'Papua New Guinea'},
        {value: 'PARAGUAY', viewValue: 'Paraguay'},
        {value: 'PERU', viewValue: 'Peru'},
        {value: 'PHILIPPINES', viewValue: 'Philippines'},
        {value: 'PITCAIRN', viewValue: 'Pitcairn Islands'},
        {value: 'POLAND', viewValue: 'Poland'},
        {value: 'PORTUGAL', viewValue: 'Portugal'},
        {value: 'PUERTO_RICO', viewValue: 'Puerto Rico'},
        {value: 'QATAR', viewValue: 'Qatar'},
        {value: 'REP_KOREA', viewValue: 'Republic of Korea'},
        {value: 'REUNION', viewValue: 'Reunion'},
        {value: 'ROMANIA', viewValue: 'Romania'},
        {value: 'RUSSIA', viewValue: 'Russian Federation'},
        {value: 'RWANDA', viewValue: 'Rwanda'},
        {value: 'SAINT_BARTHELEMY', viewValue: 'Saint Barthelemy'},
        {value: 'SAINT_HELENA', viewValue: 'Saint Helena'},
        {value: 'SAINT_KITTS', viewValue: 'Saint Kitts and Nevis'},
        {value: 'SAINT_LUCIA', viewValue: 'Saint Lucia'},
        {value: 'SAINT_MARTIN', viewValue: 'Saint Martin'},
        {value: 'SAINT_PIERRE', viewValue: 'Saint Pierre and Miquelon'},
        {value: 'SAINT_VINCENT', viewValue: 'Saint Vincent and the Grenadines'},
        {value: 'SAMOA', viewValue: 'Samoa'},
        {value: 'SAN_MARINO', viewValue: 'San Marino'},
        {value: 'SAO_TOME', viewValue: 'Sao Tome and Principe'},
        {value: 'SAUDI_ARABIA', viewValue: 'Saudi Arabia'},
        {value: 'SENEGAL', viewValue: 'Senegal'},
        {value: 'SERBIA', viewValue: 'Serbia'},
        {value: 'SEYCHELLES', viewValue: 'Seychelles'},
        {value: 'SIERRA_LEONE', viewValue: 'Sierra Leone'},
        {value: 'SINGAPORE', viewValue: 'Singapore'},
        {value: 'SLOVAKIA', viewValue: 'Slovakia (Slovak Republic)'},
        {value: 'SLOVENIA', viewValue: 'Slovenia'},
        {value: 'SOLOMON', viewValue: 'Solomon Islands'},
        {value: 'SOMALIA', viewValue: 'Somalia'},
        {value: 'SOUTH_AFRICA', viewValue: 'South Africa'},
        {value: 'SOUTH_GEORGIA', viewValue: 'South Georgia and the South Sandwich Islands'},
        {value: 'SPAIN', viewValue: 'Spain'},
        {value: 'SRI_LANKA', viewValue: 'Sri Lanka'},
        {value: 'SUDAN', viewValue: 'Sudan'},
        {value: 'SURINAME', viewValue: 'Suriname'},
        {value: 'SVALBARD', viewValue: 'Svalbard & Jan Mayen Islands'},
        {value: 'SWAZILAND', viewValue: 'Swaziland'},
        {value: 'SWEDEN', viewValue: 'Sweden'},
        {value: 'SWITZERLAND', viewValue: 'Switzerland'},
        {value: 'SYRIAN_ARAB_REP', viewValue: 'Syrian Arab Republic'},
        {value: 'TAIWAN', viewValue: 'Taiwan'},
        {value: 'TAJIKISTAN', viewValue: 'Tajikistan'},
        {value: 'TANZANIA', viewValue: 'Tanzania'},
        {value: 'THAILAND', viewValue: 'Thailand'},
        {value: 'TIMOR_LESTE', viewValue: 'Timor-Leste'},
        {value: 'TOGO', viewValue: 'Togo'},
        {value: 'TOKELAU', viewValue: 'Tokelau'},
        {value: 'TONGA', viewValue: 'Tonga'},
        {value: 'TRINIDAD', viewValue: 'Trinidad and Tobago'},
        {value: 'TUNISIA', viewValue: 'Tunisia'},
        {value: 'TURKEY', viewValue: 'Turkey'},
        {value: 'TURKMENISTAN', viewValue: 'Turkmenistan'},
        {value: 'TURKS_CAICOS', viewValue: 'Turks and Caicos Islands'},
        {value: 'TUVALU', viewValue: 'Tuvalu'},
        {value: 'UGANDA', viewValue: 'Uganda'},
        {value: 'UKRAINE', viewValue: 'Ukraine'},
        {value: 'UAB', viewValue: 'United Arab Emirates'},
        {value: 'UK', viewValue: 'United Kingdom'},
        {value: 'US_MINOR_ISLANDS', viewValue: 'United States Minor Outlying Islands'},
        {value: 'USA', viewValue: 'United States of America'},
        {value: 'URUGUAY', viewValue: 'Uruguay'},
        {value: 'UZBEKISTAN', viewValue: 'Uzbekistan'},
        {value: 'VANUATU', viewValue: 'Vanuatu'},
        {value: 'VENEZUELA', viewValue: 'Venezuela'},
        {value: 'VIETNAM', viewValue: 'Vietnam'},
        {value: 'VIRGIN_BRITISH', viewValue: 'Virgin Islands, British'},
        {value: 'VIRGIN_US', viewValue: 'Virgin Islands, U.S.'},
        {value: 'WALLIS_FUTUNA', viewValue: 'Wallis and Futuna'},
        {value: 'WESTERN_SAHARA', viewValue: 'Western Sahara'},
        {value: 'YEMEN', viewValue: 'Yemen'},
        {value: 'ZAMBIA', viewValue: 'Zambia'},
        {value: 'ZIMBABWE', viewValue: 'Zimbabwe'}
    ];
  static regions: any;

}